// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sawlpdzbovhgavlysrje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhd2xwZHpib3ZoZ2F2bHlzcmplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1ODE5MjQsImV4cCI6MjA4OTE1NzkyNH0.RxUztJByWxUSAE8yi92wsORaNyKnPSJq2HqktYVZl6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});