project_id = "sawlpdzbovhgavlysrje"

[functions.api]
verify_jwt = false

[functions.create-api-key]
verify_jwt = false

[functions.admin]
verify_jwt = false

[functions.mlbb]
verify_jwt = false

[functions.public-chat]
verify_jwt = false
